#!/bin/bash
#
# 作者：Skygangsta<skygangsta@hotmail.com>
#
# Postgres 编译脚本，仅支持 Debian 系 Linux 系统

WORK_HOME=$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)
BASE_NAME=$(basename $BASH_SOURCE)

JUMPSERVER_VERSION=1.5.6
# Jumpserver 需要 Python 3.6
ALPINE_VERSION=3.9

RANDOM_SECRET_KEY=`cat /dev/urandom | tr -dc A-Za-z0-9 | head -c 50`
RANDOM_BOOTSTRAP_TOKEN=`cat /dev/urandom | tr -dc A-Za-z0-9 | head -c 16`

function func_help() {
    echo "
使用方法:
    ${BASE_NAME} [命令]

支持的命令:
    image       创建 docker images
    help        展示 ${BASE_NAME} 脚本的帮助信息
"
}

function func_build_docker_images() {
    echo "Start building docker image..."
    # 修改 Dockerfile 中的版本信息
    if [ -z "${ALPINE_VERSION}" ]; then ALPINE_VERSION=3.9; fi

    case ${ALPINE_VERSION} in
        latest-stable)
            sed -i "s|FROM alpine:.*|FROM alpine:${ALPINE_VERSION%-*}|g" ${WORK_HOME}/Dockerfile
        ;;
        *)
            sed -i "s|FROM alpine:.*|FROM alpine:${ALPINE_VERSION}|g" ${WORK_HOME}/Dockerfile
        ;;
    esac

    sed -i "s|ARG ALPINE_VERSION=.*|ARG ALPINE_VERSION=${ALPINE_VERSION}|g" ${WORK_HOME}/Dockerfile
    sed -i "s|ARG JUMPSERVER_VERSION=.*|ARG JUMPSERVER_VERSION=${JUMPSERVER_VERSION}|g" ${WORK_HOME}/Dockerfile

    # 创建 postgresql 镜像
    docker build -t skygangsta/jumpserver-core:${JUMPSERVER_VERSION} $WORK_HOME
    
    echo "Finished."
}

case "$1" in
    image)
        func_build_docker_images

        exit 0
    ;;
    help)
        func_help
    ;;
    *)
        func_help
        exit 1
    ;;
esac
