#!/bin/bash

WORK_HOME=$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)
BASE_NAME=$(basename $BASH_SOURCE)

JUMPSERVER_VERSION=1.5.6

docker pull jumpserver/jms_guacamole:${JUMPSERVER_VERSION}
docker tag jumpserver/jms_guacamole:${JUMPSERVER_VERSION} skygangsta/jumpserver-guacamole:${JUMPSERVER_VERSION}
docker rmi jumpserver/jms_guacamole:${JUMPSERVER_VERSION}
