#!/bin/bash

WORK_HOME=$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)
BASE_NAME=$(basename $BASH_SOURCE)

JUMPSERVER_VERSION=1.5.2

func_check_source_file() {
    # 检查并安装 wget
    dpkg -V wget || sh -c "apt update && apt install -y wget"

    if [ ! -d "${WORK_HOME}/src" ]; then
        mkdir -p "${WORK_HOME}/src"
    fi

    if [ ! -s ${WORK_HOME}/src/guacamole-${JUMPSERVER_VERSION}.tar.gz ]; then
        wget https://github.com/jumpserver/docker-guacamole/archive/${JUMPSERVER_VERSION}.tar.gz \
            -O ${WORK_HOME}/src/guacamole-${JUMPSERVER_VERSION}.tar.gz
        
        if [ $? -ne 0 ]; then
            rm -rf ${WORK_HOME}/src/guacamole-${JUMPSERVER_VERSION}.tar.gz
            exit $?
        fi
    fi
}

func_check_source_file

docker pull jumpserver/jms_guacamole:${JUMPSERVER_VERSION}
docker tag jumpserver/jms_guacamole:${JUMPSERVER_VERSION} jumpserver-guacamole:${JUMPSERVER_VERSION}
docker rmi jumpserver/jms_guacamole:${JUMPSERVER_VERSION}
