#!/bin/bash
#
# 作者：Skygangsta<skygangsta@hotmail.com>
#
# Postgres 编译脚本，仅支持 Debian 系 Linux 系统

WORK_HOME=$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)
BASE_NAME=$(basename $BASH_SOURCE)

JUMPSERVER_VERSION=1.5.6

docker pull jumpserver/jms_koko:${JUMPSERVER_VERSION}
docker tag jumpserver/jms_koko:${JUMPSERVER_VERSION} skygangsta/jumpserver-koko:${JUMPSERVER_VERSION}
docker rmi jumpserver/jms_koko:${JUMPSERVER_VERSION}
