#=========================== Filebeat inputs =============================

filebeat.inputs:

- type: log
  enabled: false
  paths:
  multiline.pattern: '^\[[0-9]{4}-[0-9]{2}-[0-9]{2}'
  multiline.negate: true
  multiline.match: after

#============================= Filebeat modules ===============================

filebeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: true
  reload.period: 60s

#==================== Elasticsearch template setting ==========================

setup.template.settings:
  index.number_of_shards: 1
  index.codec: best_compression
  _source.enabled: true

#================================ General =====================================

# The name of the shipper that publishes the network data. It can be used to group
# all the transactions sent by a single shipper in the web interface.
name: filebeat

# The tags of the shipper are included in their own field with each
# transaction published.
tags: ["service-X", "web-tier"]

# Optional fields that you can specify to add additional information to the
# output.
#fields:                                                                                                
#  env: staging

#============================== Kibana =====================================

setup.kibana.host: "http://kibana:5601"

#================================ Outputs =====================================

output.elasticsearch.hosts: ["http://elasticsearch:9200"]
output.elasticsearch.username: 
output.elasticsearch.password: 

#================================ ILM =====================================

setup.ilm.enabled: auto
# %{[agent.version]}-%{+yyyy.MM.dd}
setup.ilm.rollover_alias: "filebeat-%{[agent.version]}"
setup.ilm.pattern: "{now/d}-000001"
# setup.ilm.policy_name: "filebeat-%{[agent.version]}"
# setup.ilm.policy_file: ${path.config}/policy/filebeat.json
# setup.ilm.overwrite: true

#================================ Processors =====================================

# Configure processors to enhance or manipulate events generated by the beat.

processors:
  - add_host_metadata: ~
  - add_cloud_metadata: ~
  - add_docker_metadata: ~
  - add_kubernetes_metadata: ~

#================================ Logging =====================================

# Available log levels are: error, warning, info, debug
logging.level: info
logging.selectors: ["*"]

#============================== X-Pack Monitoring ===============================

monitoring.enabled: true