#!/bin/bash
#
#


WORK_HOME=$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)
BASE_NAME=$(basename $BASH_SOURCE)

JUMPSERVER_VERSION=1.5.6

for DIR in $(ls -d */); do
    DIR=${DIR%/*}
    BUILDER=${WORK_HOME}/${DIR}/builder
    if [ -f ${BUILDER} ]; then
        sed -i "s|^JUMPSERVER_VERSION=.*$|JUMPSERVER_VERSION=${JUMPSERVER_VERSION}|g" ${BUILDER}
        chmod 755 ${BUILDER}
        ${BUILDER} $@
    else
        echo "Builder file not found: ${DIR}"
    fi
done
