#!/bin/bash
#
# 作者：Skygangsta<skygangsta@hotmail.com>
#
# Nginx 编译脚本，仅支持 Debian 系 Linux 系统

WORK_HOME=$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)
BASE_NAME=$(basename $BASH_SOURCE)

PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin:~/bin
export PATH

NGINX_VERSION=1.16.1
NGINX_VERSION_MAJOR=`printf $NGINX_VERSION | awk -F '.' '{print $1}'`
NGINX_VERSION_MINOR=`printf $NGINX_VERSION | awk -F '.' '{print $2}'`
STICKY_VERSION=1.2.6
MODSEC_BRANCH=v3/master
MODSEC_INSTALL_PATH=${WORK_HOME}/dist/modsecurity
OWASP_MODSEC_CRS_VERSION=3.2.0
ALPINE_VERSION=latest-stable


function func_help() {
    echo "
Usage:
    ${BASE_NAME} [Command]

Commands:
    image       - Build a docker image
    build       - Compile source code
    help        - Show this information
"
}

function func_build_docker_images() {
    echo "Start building docker image..."
    # 修改 Dockerfile 中的 nginx 版本
    sed -i "s/^FROM alpine:.*$/FROM alpine:${ALPINE_VERSION%-*}/g" ${WORK_HOME}/Dockerfile
    sed -i "s|ARG ALPINE_VERSION=.*|ARG ALPINE_VERSION=${ALPINE_VERSION}|g" ${WORK_HOME}/Dockerfile
    sed -i "s|ARG NGINX_VERSION=.*|ARG NGINX_VERSION=${NGINX_VERSION}|g" ${WORK_HOME}/Dockerfile
    sed -i "s|ARG STICKY_VERSION=.*|ARG STICKY_VERSION=${STICKY_VERSION}|g" ${WORK_HOME}/Dockerfile
    sed -i "s|ARG MODSEC_BRANCH=.*|ARG MODSEC_BRANCH=${MODSEC_BRANCH}|g" ${WORK_HOME}/Dockerfile
    sed -i "s|ARG OWASP_MODSEC_CRS_VERSION=.*|ARG OWASP_MODSEC_CRS_VERSION=${OWASP_MODSEC_CRS_VERSION}|g" ${WORK_HOME}/Dockerfile

    # 创建 nginx 镜像
    if [ "`echo $1 | tr a-z A-Z`" = "ENABLE-MODSEC" ]; then
        sed -i "s|ARG ENABLE_MODSEC=.*|ARG ENABLE_MODSEC=YES|g" ${WORK_HOME}/Dockerfile
        docker build -t docker.ronzxy.com/nginx:${NGINX_VERSION}-with-modsecurity $WORK_HOME
    else
        sed -i "s|ARG ENABLE_MODSEC=.*|ARG ENABLE_MODSEC=NO|g" ${WORK_HOME}/Dockerfile
        docker build -t docker.ronzxy.com/nginx:${NGINX_VERSION} $WORK_HOME
    fi
    
    echo "Finished."
}

case "$1" in
    image)
        func_build_docker_images $2
    ;;
    help)
        func_help
    ;;
    *)
        func_help
        exit 1
    ;;
esac
