#!/bin/bash
#
# Author: sky<skygangsta@hotmail.com>
#
# Postgres docker image build script

WORK_HOME=$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)
BASE_NAME=$(basename $BASH_SOURCE)

POSTGRES_VERSION=12.1
POSTGRES_VERSION_MAJOR=`printf $POSTGRES_VERSION | awk -F '.' '{print $1}'`
POSTGRES_VERSION_MINOR=`printf $POSTGRES_VERSION | awk -F '.' '{print $2}'`
ALPINE_VERSION=latest-stable

export PATH=${INSTALL_PREFIX}/bin:/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin:~/bin



function func_help() {
    echo "
Usage:
    ${BASE_NAME} [Command]

Commands:
    image       - Build a docker image
    help        - Show this information
"
}

function func_build_docker_images() {
    echo "Getting the latest version of the extensions..."
    CITUS_VERSION=$(wget -qO - "https://api.github.com/repos/citusdata/citus/releases/latest" | grep '"tag_name": ".*' | awk -F: '{print $2}' | awk -F '"' '{print $2}' | awk -Fv '{print $2}')
    HLL_VERSION=$(wget -qO - "https://api.github.com/repos/citusdata/postgresql-hll/releases/latest" | grep '"tag_name": ".*' | awk -F: '{print $2}' | awk -F '"' '{print $2}' | awk -Fv '{print $2}')
    POSTGIS_VERSION=$(wget -qO - http://download.osgeo.org/postgis/source/ | grep -o title=\"postgis-.*.tar.gz\" | grep -v alpha | grep -v beta | grep -v rc | awk -F\" '{print $2}' | awk -F- '{print $2}' | awk -F.tar '{print $1}' | sort -rk 1 | head -n 1)

    echo "Start building docker image..."
    # 修改 Dockerfile 中的版本信息
    if [ -z "${ALPINE_VERSION}" ]; then ALPINE_VERSION=latest-stable; fi

    case ${ALPINE_VERSION} in
        latest-stable)
            sed -i "s|FROM alpine:.*|FROM alpine:${ALPINE_VERSION%-*}|g" ${WORK_HOME}/Dockerfile
        ;;
        *)
            sed -i "s|FROM alpine:.*|FROM alpine:${ALPINE_VERSION}|g" ${WORK_HOME}/Dockerfile
        ;;
    esac

    sed -i "s|ARG ALPINE_VERSION=.*|ARG ALPINE_VERSION=${ALPINE_VERSION}|g" ${WORK_HOME}/Dockerfile
    sed -i "s|ARG POSTGRES_VERSION=.*|ARG POSTGRES_VERSION=${POSTGRES_VERSION}|g" ${WORK_HOME}/Dockerfile
    sed -i "s|ARG CITUS_VERSION=.*|ARG CITUS_VERSION=${CITUS_VERSION}|g" ${WORK_HOME}/Dockerfile
    sed -i "s|ARG HLL_VERSION=.*|ARG HLL_VERSION=${HLL_VERSION}|g" ${WORK_HOME}/Dockerfile
    sed -i "s|ARG POSTGIS_VERSION=.*|ARG POSTGIS_VERSION=${POSTGIS_VERSION}|g" ${WORK_HOME}/Dockerfile
    # 创建 Postgres 镜像
    docker build -t skygangsta/postgres:${POSTGRES_VERSION} $WORK_HOME
    
    echo "Finished."
}

case "$1" in
    image)
        func_build_docker_images

        exit 0
    ;;
    help)
        func_help
    ;;
    *)
        func_help
        exit 1
    ;;
esac
